apply plugin: "com.android.library"

android {
    compileSdk 35
    namespace "com.parse.coroutines"

    defaultConfig {
        minSdk 23
        targetSdk 35
    }

    buildFeatures {
        buildConfig true
    }

    buildTypes {
        debug {
            buildConfigField("String","PARSE_VERSION","\"${version}\"")
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
            buildConfigField("String","PARSE_VERSION","\"${version}\"")
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

ext {
    coroutinesVersion = "1.6.1"
}

dependencies {
    api "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.22"
    api "org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutinesVersion"
    api "org.jetbrains.kotlinx:kotlinx-coroutines-android:$coroutinesVersion"
    implementation project(":parse")
}
