apply plugin: "com.android.library"
apply plugin: "maven-publish"

android {
    compileSdk 35
    namespace "com.parse.facebook"

    defaultConfig {
        minSdk 23
        targetSdk 35
    }

    buildFeatures {
        buildConfig true
    }

    lint {
        abortOnError false
    }

    buildTypes {
        debug {
            enableAndroidTestCoverage = true
            enableUnitTestCoverage = true
            buildConfigField("String","PARSE_VERSION","\"${version}\"")
        }
        release {
            minifyEnabled false
            enableAndroidTestCoverage = false
            enableUnitTestCoverage = false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
            buildConfigField("String","PARSE_VERSION","\"${version}\"")
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    api "com.facebook.android:facebook-login:[13.2.0, 17.0.0["
    implementation project(":parse")

    testImplementation "junit:junit:$rootProject.ext.junitVersion"
    testImplementation "org.mockito:mockito-core:$rootProject.ext.mockitoCoreVersion"
    testImplementation "org.mockito:mockito-inline:$rootProject.ext.mockitoCoreVersion"
    testImplementation "org.robolectric:robolectric:$rootProject.ext.robolectricVersion"
}
