apply plugin: "com.android.library"
apply plugin: "maven-publish"

android {
    compileSdk 35
    namespace "com.parse.google"

    defaultConfig {
        minSdk 23
        targetSdk 35
    }

    buildFeatures {
        buildConfig true
    }

    lint {
        abortOnError false
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildTypes {
        debug {
            enableAndroidTestCoverage = true
            enableUnitTestCoverage = true
            buildConfigField("String","PARSE_VERSION","\"${version}\"")
        }
        release {
            minifyEnabled false
            enableAndroidTestCoverage = false
            enableUnitTestCoverage = false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
            buildConfigField("String","PARSE_VERSION","\"${version}\"")
        }
    }

}

dependencies {
    api "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    api "com.google.android.gms:play-services-auth:20.2.0"
    api "androidx.activity:activity-ktx:1.5.1"
    api "androidx.fragment:fragment-ktx:1.5.2"
    implementation project(":parse")
}
