apply plugin: "com.android.library"
apply plugin: "maven-publish"

android {
    compileSdk 35
    namespace "com.parse.twitter"

    defaultConfig {
        minSdk 23
        targetSdk 35
    }

    buildFeatures {
        buildConfig true
    }

    lint {
        abortOnError false
    }

    buildTypes {
        debug {
            enableAndroidTestCoverage = true
            enableUnitTestCoverage = true
            buildConfigField("String","PARSE_VERSION","\"${version}\"")
        }
        release {
            minifyEnabled false
            enableAndroidTestCoverage = false
            enableUnitTestCoverage = false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
            buildConfigField("String","PARSE_VERSION","\"${version}\"")
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    api "androidx.appcompat:appcompat:1.5.0"
    api "oauth.signpost:signpost-core:2.1.1"
    api "se.akerfeldt:okhttp-signpost:1.1.0"
    implementation project(":parse")

    testImplementation "junit:junit:$rootProject.ext.junitVersion"
    testImplementation "org.mockito:mockito-core:$rootProject.ext.mockitoCoreVersion"
}
